### ISSUE TITLE
Revisar bug en hover sobre textos explicativos

### ISSUE THREAD

**Issue by davo** [gcba/inscripciones-escolares-2015#42]
Las clases de animate.css le ganan a la opacidad transicionada.

Posible solución: Eliminar clases de animate luego de que se carga la sección.

**Comment by pilimayora** [comment]
Las clases de animate en los textos eran las que causaban el problema.
Dejé las clases en el grupo de textos pero las saqué de los textos mismos y volvió todo a la normalidad :)
