### ISSUE TITLE
Contenidos: Definir por secciones

### ISSUE THREAD

**Issue by davo** [gcba/inscripciones-escolares-2015#47]

**Comment by ghost** [comment]
VISTA 1:
Bajada:
El 9 de marzo cerró el periodo de inscripción y asignación escolar de 2015, por el que pasaron todos aquellos alumnos que ingresaron  por primera vez a una escuela de gestión estatal o quienes cambiaron de nivel educativo.

Con 1 círculo representamos 500 nuevos alumnos en el sistema.

Mirá el total de nuevos alumnos.

**Comment by ghost** [comment]
VISTA 2:

Total de nuevos alumnos del sistema educativo de gestión estatal de la Ciudad.

Con este conjunto círculos representamos los 63000 nuevos alumnos del sistema educativo. 

Mirá como se dividen en niveles.

**Comment by ghost** [comment]
VISTA 3

Nuevos alumnos del sistema educativo de gestión estatal de la Ciudad.

Mirá como se distribuyen por comunas.

**Comment by ghost** [comment]
VISTA 4

Nuevos alumnos del sistema educativo de gestión estatal de la Ciudad, por nivel y comuna.

Texto nivel inicial: Las comunas 4, 7 y 8 concentran el 37% de los nuevos alumnos de nivel inicial.
Texto nivel primario: Las comunas 4, 8 y 9 concentran el 33% de los nuevos alumnos de nivel primario.
Texto nivel secundario: Las comunas 3, 4 y 9 concentran el 30% de los nuevos alumnos de nivel secundario.

Navegá el mapa de las escuelas.
